version: '3.9'

services:
  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    working_dir: /app/db
    ports:
      - "3000:3000"
    volumes:
      - ./db:/app/db
    command: node index.js
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app/frontend
    ports:
      - "5173:5173"
      - "24678:24678" # Vite HMR port
    volumes:
      - ./frontend:/app/frontend
    command: yarn dev
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=${NODE_ENV}
      - VITE_ENTRYPOINT_ADDRESS=${ENTRYPOINT_ADDRESS}
      - VITE_ZK_EMAIL_VERIFIER_EMAIL=${ZK_EMAIL_VERIFIER_EMAIL}
      - VITE_ZK_EMAIL_VERIFIER_URL=${ZK_EMAIL_VERIFIER_URL}
      - VITE_ZK_PASSPORT_VERIFIER_ADDRESS=${ZK_PASSPORT_VERIFIER_ADDRESS}

volumes:
  db_node_modules:
  frontend_node_modules:
  mongodb_data:
